export const STR = {
  title: "ASTEROID DRIFT",
  subtitle: "Destruidor de asteroides",
  startPrompt: "Pressione ESPAÇO ou toque em FOGO para começar",
  pausedLabel: "PAUSADO",
  resumeHint: "Pressione P ou ESC para continuar",
  scoreLabel: "Pontos",
  livesLabel: "Vidas",
  highScoreLabel: "Recorde",
  gameOverTitle: "NAVE DESTRUÍDA",
  gameOverHint: "Pressione ESPAÇO ou toque para reiniciar",
  settingsTitle: "Configurações",
  settingsClose: "Fechar (ESC)",
  vectorToggleLabel: "Mostrar vetores de velocidade",
  vectorToggleHint: "Visualiza como cada asteroide se move — a seta indica direção e velocidade",
  soundToggleLabel: "Som",
  difficultyLabel: "Dificuldade",
  difficultyEasy: "Fácil",
  difficultyNormal: "Normal",
  difficultyHard: "Difícil",
  controlsHint: "Mover: Setas / WASD / Analógico — Atirar: Espaço / Botão A",
  settingsButton: "Configurações (Esc)",
  vectorLegendSpeed: "vel",
  vectorLegendDir: "dir",
  fireZone: "FOGO",
  touchHintMove: "arraste para mover",
};
